services:
  mysql:
    container_name: container-mysql
    build:
      context: ./db
    environment:
      - MYSQL_ROOT_PASSWORD=${password}
      - MYSQL_DATABASE=${database}
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - rede-pdsi2

  aplicacao:
    container_name: container-aplicacao
    build:
      context: ./app
    command: ["./entrypoint.sh"]
    depends_on:
      - mysql
    ports:
      - 3000:3000
    networks:
      - rede-pdsi2

volumes:
  mysql-data:

networks:
  rede-pdsi2:
    driver: bridge